steps:
    # Build the Container
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-web-server-cloud-run:$COMMIT_SHA', '.']
    # Push with Commit SHA as Tag
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/hello-web-server-cloud-run:$COMMIT_SHA']
    # Also add the latest tag
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/hello-web-server-cloud-run:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/hello-web-server-cloud-run:latest' ]
    # Deploy to Cloud Run
      - name: 'gcr.io/cloud-builders/gcloud'
      args:
        - 'run'
        - 'deploy'
        - 'hello-web-server-cloud-run'
        - '--image'
        - 'gcr.io/$PROJECT_ID/hello-web-server-cloud-run:$COMMIT_SHA'
        - '--region'
        - 'europe-west1'
        - '--platform'
        - 'managed'
        - '--allow-unauthenticated'